version: "3.5"

services:
  app:
    build: .
    volumes:
      - ".:/app"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://db:27017
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - "27017:27017"
